language: python

install:
  - pip install
  - pip install gitpython

script:
  - cd _tools/
  - travis_retry python create_repo.py

deploy:
  provider: pages
  skip_cleanup: true
  local-dir: pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master   
